### ISSUE TITLE
Authentification

### ISSUE THREAD

**Issue by thomas-bouvier** [Dominique57/FlexomUnofficialApi#6]
Bonjour Dominique,

J'ai un système Flexom V3 chez moi. J'utilise uniquement l'application mobile fournie par Overkiz pour contrôler mon éclairage et mes volets. Votre API pourrait-elle me permettre de supplanter l'application Flexom V3 ?

J'ai essayé d'utiliser votre code en renseignant le mail ainsi que le mot de passe que j'utilise sur Flexom V3, mais j'obtiens l'erreur suivante :

```
Traceback (most recent call last):
  File "/home/Dev/FlexomUnofficialApi/test.py", line 3, in <module>
    user_client = UserClient.build_client("mail@gmail.com", "motdepasse")
  File "/home/Dev/FlexomUnofficialApi/flexomapi/clients/user_client.py", line 19, in build_client
    user_token = authenticator.get_user_token()
  File "/home/Dev/FlexomUnofficialApi/flexomapi/clients/user_authenticator.py", line 23, in get_user_token
    ).handle_or_throw()
  File "/home/Dev/FlexomUnofficialApi/flexomapi/requests/request_handler.py", line 70, in handle_or_throw
    raise Exception(f"Failed to fetch dto, err code `{err}`")
Exception: Failed to fetch dto, err code `Error.HTTP_CODE`
```

Merci !

**Comment by thomas-bouvier** [comment]
Après quelques recherches, il semble que la solution Flexom V2 utilise le cloud d'Ubiant, c'est bien ce que semble vers ce projet. La solution Flexom V3 utilise quant à elle Overkiz cloud. Je vais donc utiliser quelque chose d'autres.

iMicknl/python-overkiz-api#378
https://github.com/iMicknl/python-overkiz-api/blob/e4d37f23a7decdf4b93dd2645550db3fb0c681c2/pyoverkiz/const.py
